web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ../:/app
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  environment:
    DEBUG: 'true'

php:
  build: ./
  volumes:
    - ../:/app
  links:
    - db

db:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: app_db
    MYSQL_ROOT_PASSWORD: K;)e)fG6rHTe>4Hunf3P
    MYSQL_USER: app_user
    MYSQL_PASSWORD: yfKLR73;YTs3i;U2TXd7
