web:
  build: ./
  ports:
    - "80:80"
  volumes:
    - ../:/app
  environment:
    DEBUG: 'true'
    ALLOW_OVERRIDE: 'true'

db:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: app_db
    MYSQL_ROOT_PASSWORD: K;)e)fG6rHTe>4Hunf3P
    MYSQL_USER: app_user
    MYSQL_PASSWORD: yfKLR73;YTs3i;U2TXd7
